# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

swift_version= '5.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  source 'https://github.com/CocoaPods/Specs.git'

  # Pods for RxStoreKit
  pod 'RxStoreKit', :path => '../'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
